-- Plugins
require('plugins.symbols-outline')
require('plugins.illuminate')
require('plugins.toggleterm_init')
require('plugins.treesitter-context')
require('plugins.copilot')
require("plugins.colorscheme")
require("plugins.autopairs")
require("plugins.align")
require("plugins.web-devicons")
require("plugins.inc_rename")
require("plugins.todo-comments")
require("plugins.zen-mode")
require("plugins.rust-vim")
require("plugins.minimap")
require("plugins.lualine")
